# Generated by Django 5.2.6 on 2025-09-18 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='closing_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('Income', 'Income'), ('EXPENSE', 'Expense')], max_length=10),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='account_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outflows', to='cashbook.account'),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='account_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inflows', to='cashbook.account'),
        ),
    ]
