# Generated by Django 5.2.6 on 2025-09-18 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0002_account_cashtransaction_closing_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cashtransaction',
            name='account_from',
        ),
        migrations.RemoveField(
            model_name='cashtransaction',
            name='account_to',
        ),
        migrations.AddField(
            model_name='account',
            name='code',
            field=models.CharField(choices=[('CASH', 'Cash Account'), ('BANK', 'Bank/GPay Account'), ('PENDING', 'Pending Account')], default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashbook.account'),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=10),
        ),
    ]
