# Generated by Django 5.2.6 on 2025-09-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0003_remove_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(choices=[('CASH', 'Cash Account'), ('BANK', 'Bank/GPay Account'), ('PENDING', 'Pending Account')], default='CASH', max_length=20, unique=True),
        ),
    ]
