# Generated by Django 5.2.6 on 2025-09-19 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0004_alter_account_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransaction',
            name='reference_user',
            field=models.ForeignKey(blank=True, help_text='Select who referred the work (leave empty for Direct)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
