# Generated by Django 5.2.6 on 2025-09-19 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0005_cashtransaction_reference_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransaction',
            name='settled_from',
            field=models.ForeignKey(blank=True, help_text='Links back to pending transaction if this is a settlement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements', to='cashbook.cashtransaction'),
        ),
    ]
