# Generated by Django 5.2.6 on 2025-09-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0006_cashtransaction_settled_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransaction',
            name='settled',
            field=models.BooleanField(default=False),
        ),
    ]
