# Generated by Django 5.2.6 on 2025-09-24 17:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklog',
            name='check_in_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
